title = "Styx Configuration File"

[server]
port = 80
server_name = "my_url"

[Default]
default_route = "route par defaut"

[[hosts]]
name = "google"
entrypoint = "url"
ip = "8.8.8.8"
port = 8080

[[hosts]]
name = "localhost"
entrypoint = "url"
ip = "127.0.0.0"
port = 3606

[[hosts]]
name = "localhost2"
entrypoint = "url"
ip = "127.0.0.0"
port = 8080

[DDOS_Parameters]
max_request = 10000
max_request_per_user = 100
verification_timer = 180 #in seconds